### ISSUE TITLE
Miscalculated diagnostic width when using multibyte characters

### ISSUE THREAD

**Issue by Saviq** [MirServer/ubuntu-frame#149]
```
echo "lasczz" > diagnostic.txt
```
<img src=https://github.com/MirServer/ubuntu-frame/assets/231077/3d987280-3c07-4da9-98be-86ae27340495 width=50%/>

vs.

```
echo "łąśćźż" > diagnostic.txt
```
<img src=https://github.com/MirServer/ubuntu-frame/assets/231077/01647eee-502b-430c-9fad-5440138913e7 width=50%/>

**Comment by AlanGriffiths** [comment]
Seems likely. `render_text(()` is calling `TextRenderer::get_max_font_height_by_width()` with the the raw utf8 string, and the later is is assuming that each code unit is a character (as in latin1). (The actual rendering first converts to utf32 so that code unit == character is a reasonable assumption.)

I think we simply need to do the conversion to utf32 earlier.
